### ISSUE TITLE
Create the website

### ISSUE THREAD

**Issue by matthewp** [bitovi/velocirender#12]
Here's what it currently looks like:

<img width="1338" alt="screen shot 2019-01-23 at 2 40 44 pm" src="https://user-images.githubusercontent.com/361671/51632327-0894e880-1f1d-11e9-8def-f05f426ff744.png">

The UI elements it should have are:

1. A hero area for branding stuff.
1. A quick installation / usage example (the code shown in the above).
1. A demo area that shows incremental vs. client apps side-by-side.
    * Shows tabs for various frameworks.
    * Shows a refresh button to reload the examples.

**Comment by matthewp** [comment]
Example of the site is shown here: https://github.com/bitovi/bitovi/issues/219

**Comment by matthewp** [comment]
Important links:

* [Getting Started](https://github.com/bitovi/velocirender/blob/master/docs/getting-started.md)
* Article (link tbd)
* [GitHub repo](https://github.com/bitovi/velocirender)
* Demo apps
  * [React](https://github.com/bitovi/dog-things-react)
  * [Vue](https://github.com/bitovi/dog-things-vue)
  * [Angular](https://github.com/bitovi/dog-things-angular)

**Comment by adrifolio** [comment]
@matthewp @justinbmeyer here's the first concept I came up with:

![velocirender splash page 01](https://user-images.githubusercontent.com/950214/51841752-ec09ff00-22d4-11e9-8061-ff235d6bfc76.png)

Let me know your thoughts!

**Comment by matthewp** [comment]
This looks superb.

**Comment by adrifolio** [comment]
Thank you! :)


I created this branch https://github.com/bitovi/velocirender/tree/styles to work on the styles and are half way there:

<img width="1918" alt="screen shot 2019-01-29 at 8 06 37 am" src="https://user-images.githubusercontent.com/950214/51913849-1aeba800-239d-11e9-9bb4-5a91c2c3ede4.png">


 I'm gonna work some more tonight and should have a more finished version tomorrow morning.

**Comment by matthewp** [comment]
Ok, great! The `Loading!` page is in `docs/loading.html` if you want to change how that looks.

**Comment by adrifolio** [comment]
Definitely! Thanks for pointing that out!

**Comment by matthewp** [comment]
Hey Adri, I think you might have increased the height of the iframes. On my monitor it now is taller than my viewport, so to get to the refresh button I have to scroll so that the top of the demo page is not visible.

<img width="1409" alt="screen shot 2019-01-29 at 3 01 01 pm" src="https://user-images.githubusercontent.com/361671/51936720-d3820d80-23d6-11e9-8955-340518ef0496.png">

I'm guessing you did this so the rest of the items would be visible.  I sort of wanted the same thing, but I'm not sure how that will be possible aside from shrinking the entire thing.  I wonder if `scale()` would work here? 🤔

Anyways, I do think the entire frame should be visible in the viewport, although I don't know what the best solution is here.

**Comment by adrifolio** [comment]
Yes I did, and I failed to communicate that :( 
I was going by my viewport where the height is 1050px. Should we target 900 or 800?

I have not tried `scale()` but I can take a look and see if that works.

**Comment by matthewp** [comment]
I'm not sure, how can I find out what my viewport height is?

**Comment by adrifolio** [comment]
I'm looking under the monitor display settings (right below the laptop pic)
<img width="690" alt="screen shot 2019-01-29 at 3 14 09 pm" src="https://user-images.githubusercontent.com/950214/51940824-a898b900-23d8-11e9-9bcc-3ea6ede8084d.png">

**Comment by adrifolio** [comment]
Hey @matthewp I noticed the installation code block looks different locally than remotely:

locally:
<img width="1087" alt="screen shot 2019-01-29 at 1 40 52 pm" src="https://user-images.githubusercontent.com/950214/51941824-2362d380-23db-11e9-8259-99d538845022.png">

remotely:
<img width="1428" alt="screen shot 2019-01-29 at 3 28 45 pm" src="https://user-images.githubusercontent.com/950214/51941886-43929280-23db-11e9-9574-834e9e796c96.png">

I see why, so the question is if you think the code beautifier is needed.

**Comment by matthewp** [comment]
Yeah, that's likely not needed. I'll remove it.

**Comment by matthewp** [comment]
I think this can be closed!
