### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by matthewp** [bitovi/velocirender#27]
This project is currently called __incremental__.  This is named after the technique we developed, *incremental rendering*. So there's at present no branding around it. Given that this project is unique and available broadly (should work with any framework) we should think about whether it's worth giving it some branding.

Ideas the name/color scheme should invoke:

* Raw speed
* Accelerated application boot time
* Resiliency to network conditions
* Of Bitovi

ccing branding enthusiasts @tomgreever @moschel @justinbmeyer @kylegifford

**Comment by justinbmeyer** [comment]
Fastforward

**Comment by tomgreever** [comment]
Velocirender 


![bbca](https://user-images.githubusercontent.com/326843/51415556-d1e55980-1b3b-11e9-851a-6345afec5c9c.gif)

**Comment by tomgreever** [comment]
Raw speed... extreme flexibility... resiliency to environment... it's... VELOCIRENDER
