### ISSUE TITLE
Fix text alignment in the console area

### ISSUE THREAD

**Issue by chasenlehara** [bitovi/velocirender#50]
I think it should either be left-aligned or “centered”

<img width="1000" alt="screen shot 2019-02-06 at 11 57 20 am" src="https://user-images.githubusercontent.com/10070176/52371457-73a8e980-2a0a-11e9-8c66-feb0cc851e3b.png">

**Comment by adrifolio** [comment]
Yes, just need to remove the "pre" styles that are creating that huge gap... don't ask me why.
