### ISSUE TITLE
Add Email Capture to Website

### ISSUE THREAD

**Issue by adrifolio** [bitovi/velocirender#57]
Along the lines of "Need help? Contact Us" with a link to  https://www.bitovi.com/streamable#hs_cos_wrapper_widget_1485893088244.

This could go above the article block.

**Comment by adrifolio** [comment]
@moschel @matthewp this is what I had in mind:

<img width="984" alt="screen shot 2019-02-11 at 7 52 15 am" src="https://user-images.githubusercontent.com/950214/52567481-0c0be900-2dd2-11e9-8327-9dfc99e8db89.png">

**Comment by matthewp** [comment]
Looks great!

**Comment by moschel** [comment]
Looks good to me!
